remote_theme: jekyll-theme-academic-pages
title: Mon portfolio de doctorant
description: Ce site web en Markdown est mon portfolio de doctorant. Il a pour but de présenter de manière réflexive les compétences que je développe durant mon doctorat en Sciences de l'Information et de la Communication (SIC). Ce site sera enrichi tout au long du doctorat.
